name: ebac-tests-api-cy-ci

on:
  push:
    branches: [ ci ]
    
  workflow_dispatch:
  
jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: npm

      - name: Install
        run: npm install

      - name: Cypress run
        uses: cypress-io/github-action@v5
        continue-on-error: true
        with:
          browser: chrome
          run: npm run ci

      - name: Publish Report
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./mochawesome-report
